#!/bin/bash
#
# SEO Prep Flow - Step 4: Create Prep Report
# Runs: Saturday 19:30 PST
# Output: /tmp/seo-data/prep-report.md
#

set -e

OUTPUT_DIR="/tmp/seo-data"
BLOGS_DIR="/tmp/seo-data/blogs"

echo "═══════════════════════════════════════════════════"
echo "📊 Step 4: Create Prep Report"
echo "⏰ $(date '+%Y-%m-%d %H:%M:%S')"
echo "═══════════════════════════════════════════════════"

REPORT_FILE="$OUTPUT_DIR/prep-report.md"

# Generate report
cat > "$REPORT_FILE" <<EOF
# MiniAIPDF SEO Prep Report

**Generated**: $(date '+%Y-%m-%d %H:%M:%S PST')
**Status**: ✅ Ready for Deployment

---

## 📋 Summary

This week's SEO content has been prepared and is ready for deployment.

---

## 🔑 Keywords Selected

EOF

# Add keywords
if [ -f "$OUTPUT_DIR/keywords.json" ]; then
    cat "$OUTPUT_DIR/keywords.json" | jq -r '.keywords[] | "| \(.priority). | \(.keyword) | \(.volume) | \(.difficulty) |"' >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" <<EOF

| Priority | Keyword | Volume | Difficulty |
|----------|---------|--------|------------|

---

## 📝 Blogs Generated

EOF

# Add blog list
if [ -d "$BLOGS_DIR" ]; then
    for blog_dir in "$BLOGS_DIR"/blog-*; do
        if [ -d "$blog_dir" ]; then
            METADATA="$blog_dir/metadata.json"
            if [ -f "$METADATA" ]; then
                SLUG=$(cat "$METADATA" | jq -r '.slug')
                KEYWORD=$(cat "$METADATA" | jq -r '.keyword')
                echo "- [ ] **$KEYWORD** → /blog/$SLUG" >> "$REPORT_FILE"
            fi
        fi
    done
fi

cat >> "$REPORT_FILE" <<EOF

---

## 🐦 Social Copy Ready

| Platform | Status |
|----------|--------|
| Twitter | ✅ Ready |
| LinkedIn | ✅ Ready |

---

## ✅ Deployment Checklist

- [ ] Main Flow can now deploy content
- [ ] Twitter posts scheduled
- [ ] Telegram report configured

---

## 📅 Next Steps

1. **Saturday-Sunday**: Optional review of generated content
2. **Monday 09:00 PST**: Main Flow auto-deploys content
3. **Ongoing**: Monitor rankings and engagement

---

*Generated by MiniAIPDF SEO Prep Flow*
EOF

echo "✅ Report saved to: $REPORT_FILE"

echo ""
echo "═══════════════════════════════════════════════════"
echo "✅ PREP FLOW COMPLETE!"
echo "═══════════════════════════════════════════════════"
echo ""
echo "Content is ready for deployment."
echo "Main Flow will run Monday 09:00 PST."
